name: vpn_master
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  uuid: ^4.5.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_v2ray: ^1.0.10
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  #flutter_local_notifications: ^19.2.0
  get_it: ^8.0.3
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  flutter_spinkit: ^5.2.1
  http: ^1.4.0
  device_info_plus: ^11.4.0
  flutter_dotenv: ^5.2.1
  mongo_dart: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  fullscreen: true
  android_12:
    image: assets/images/splash_logo.png
    color: "#FFFFFF"
